### ISSUE TITLE
When Simulator mode, controller-type doesn't affect

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_pr2eus#135]
When I set the controller-type at init like `(instance baxter-interface :init :type :larm-controller)` or `(instance pr2-interface :init :type :larm-controller)`,
I expect the baxter or pr2 will move only their larm, but it doesn't.

Around below code?
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L278

Test code is like below

For baxter
```
(setq *ri* (instance baxter-interface :type :larm-controler))
(setq *baxter* (instance baxter-robot :init))
(send *baxter* :untuck-pose)
(send *ri* :angle-vector (send *baxter* :angle-vector) 5000)
```

For pr2
```
(setq *ri* (instance pr2-interface :type :larm-controler))
(setq *pr2* (instance pr2-robot :init))
(send *pr2* :reset-manip-pose)
(send *ri* :angle-vector (send *pr2* :angle-vector) 5000)
```

**Comment by wkentaro** [comment]
This will be solved via https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/140
