### ISSUE TITLE
error in simulator

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_pr2eus#142]
I have this error:
```
/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: integer expected in (elt next-av id)
```

It may be caused by the change on 936e929.

**Comment by k-okada** [comment]
what is you input?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
```
(send *ri* :angle-vector (send *baxter* :untuck-pose))
```

**Comment by k-okada** [comment]
fixed in https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/143
and https://github.com/jsk-ros-pkg/jsk_robot/pull/335

if you merge one of these, this problem will be fixed

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Fixed.
Thanks.
