### ISSUE TITLE
pr2の:go-posはブロックする？

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_pr2eus#160]
```
:go-pos
```
するとゴールにつくまで帰ってこない？帰ってくる？
hrp2は
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L716

:go-pos, :go-pos-no-wait, :wait-foot-step
があるみたいだけど，同様なのはないんだっけ？

動きながら，手を動かす，みたいなコードはどうやって書いている？ @h-kamada

**Comment by h-kamada** [comment]
go-posは返ってこないものだと思ってます。(後で調べます)
少なくともgo-pos-unsafeは返ってきません。
卒論の時に書いたコードでは、手とbaseの動きがしっかり連動して欲しかったのでgo-pos-unsafeを用いていましたが、これは終わるまで返ってこないので、関数内でwaitしている部分だけ除いて使っていました。
hrp2でもそのような関数があるのならばPR2でもそのような関数を足しても良いでしょうか。

**Comment by k-okada** [comment]
なるほど，関数は
:go-pos
:go-pos-no-wait
:go-wait (go-pos をwaitする）
:go-stop (止まる．これはもうある）
にしましょうか．

作っとくので，それを前提にデモ関数を変えていって下さい．

ところで
冷蔵庫デモをeuslispだけでやるのはどうするの？
https://github.com/jsk-ros-pkg/jsk_demos/tree/master/detect_cans_in_fridge_201202
? Readme つくっておいて，

https://github.com/jsk-ros-pkg/jsk_demos みたいに，
またこのjsk_demos/README.mdは
https://github.com/jsk-ros-pkg/jsk_demos/tree/master/jsk_2013_04_pr2_610
に統合して，トップページはカッコいい写真とリンクの羅列にしようか．


--
◉ Kei Okada


2015-08-07 11:56 GMT+09:00 h-kamada <notifications@github.com>:

**Comment by h-kamada** [comment]
> なるほど，関数は :go-pos :go-pos-no-wait :go-wait (go-pos をwaitする） :go-stop (止まる．これはもうある） にしましょうか．
:go-pos と:go-waitの違いは何でしょうか。

また、go-pos-unsafeのwait有り無しバージョンは作らないのでしょうか？

**Comment by k-okada** [comment]
go-pos = go-pos-no-wait + go-wait

にします．go-wait はgoと付いていますが，進まず待つだけです．go-stopが止まるだけなのように．

go-pos-unsafeもつくってもいいですが，基本は全てgo-posで動くはずです．（うまくコストマップを替える等々）

--
◉ Kei Okada


2015-08-07 15:15 GMT+09:00 h-kamada <notifications@github.com>:

**Comment by k-okada** [comment]
> 冷蔵庫デモをeuslispだけでやるのはどうするの？
> https://github.com/jsk-ros-pkg/jsk_demos/tree/master/detect_cans_in_fridge_201202 ? Readme つくっておいて，

以下で必要 https://github.com/himlen1990/todo/issues/1

**Comment by h-kamada** [comment]
確認しましたが、go-pos も終了するまで返って来ません。

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/162

で，go-pos, go-pos-no-wait を足しました．一発で動く気がしないので，書くにして下さい．

あと，元のコードからですが，
map-to-frame が解決できた時と出来ないときで，wait
のwhen ret いかでちゃんと対応出来ていない気がします．


--
◉ Kei Okada

**Comment by h-kamada** [comment]
> あと，元のコードからですが， map-to-frame が解決できた時と出来ないときで，wait のwhen ret いかでちゃんと対応出来ていない気がします．

これは#157 であげられていた問題でしょうか？
> [ERROR] [1438838240.968802675]: "map" passed to lookupTransform argument
> target_frame does not exist
> ```
> message, but everything working well, is it correct? if so please write
> issue for this. Displaying  error, but works good is confusing.

もしそうであれば jsk-ros-pkg/jsk_demos#1026 のPRで解決できたと思っているのですが...

**Comment by k-okada** [comment]
ちがいます．
また，上のerrorは
             (map-to-frame (send *tfl* :lookup-transform "/map" frame-id
(ros::time 0)))
ででるけど，simulation-modep の時もこのコードにはいって，でも使わない，というのが問題では

--
◉ Kei Okada

**Comment by k-okada** [comment]
Cf: https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/163
