### ISSUE TITLE
:go-pos, simulation-modep だと絶対位置指令だが大丈夫？

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_pr2eus#161]
:go-pos 実機は相対指令ですが，:simulation-modep は絶対指令な気がする

https://github.com/jsk-ros-pkg/jsk_demos/pull/1008
とか，irtdemoはどうしている？spotベースでmove-to を使っているから大丈夫とか？そういう感じでしょうか．

**Comment by h-kamada** [comment]
fridge demoはまだeuslisp 上では動かせていません。
irtdemoでは、ある場所に移動する部分はおっしゃる通りspotベースでmove-toを使って移動しています。
そこからの微妙な動きはgo-pos-unsafeを使っています。
go-pos-unsafe はsimulationでも相対指令のようなのでこれでうまく行っていると思われます。
irtdemoでは見る限りではgo-posは使っていないようです。

**Comment by k-okada** [comment]
> fridge demoはまだeuslisp 上では動かせていません。

何かブロックしている問題があったらissue出しておいてください
