### ISSUE TITLE
pr2 Kinematics Simulatorでロボットにobjectを:assoc/:dissocしたい

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_pr2eus#178]
![pr2_tea](https://cloud.githubusercontent.com/assets/1901008/10881487/6c37ba06-81a6-11e5-9d9f-0822b37a3b1b.png)

pr2 kinematics simulatorで物体の把持などを可視化したい時はどうしたらいいでしょうか？

**Comment by k-okada** [comment]
send *ri* :robot :assoc (elt (send *ri* :objects) 0)
かな
send *ri* :find-object
とかあってもいいかもしれない。
https://github.com/euslisp/jskeus/blob/master/irteus/irtscene.l みたいに

--
◉ Kei Okada

2015/11/02 21:12、Furushchev <notifications@github.com> のメッセージ:

**Comment by furushchev** [comment]
:assocする対象は1つなので、どちらのrobotにassocさせるかという問題がある木がします。
例えば

```
(send (send (send *pr2* :rarm :end-coords) :parent) :assoc *cup*)
(send (send (send *ri* :robot :rarm :end-coords) :parent) :assoc *cup*)
```

とすると、最初の`*pr2*`にassocされるため、`(send *ri* :robot)`へのassocは失敗(無視)します。

```
(send *ri* :objects (list *cup*)
```

したときにメソッド内部でcopy-objectするというのが考えられますが、これは元のobjectをtransformしたときにずれて行ってしまうので、微妙な気もします。。。

**Comment by furushchev** [comment]
robot-interfaceの`:objects`メソッド内でcopy-objectしているようなので、これで目的は達成できそうです。
ありがとうございました。
