### ISSUE TITLE
pr2-interfaceでgripperの現在のposition(グリッパー間が何rad (or m)か？)を知りたい

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_pr2eus#181]
現在実機では

```
4.-irteusgl$ send *ri* :start-grasp :rarm
;; #<rotational-joint #Xa1bfa00 r_elbow_flex_joint> :joint-angle(-121.624) violate min-angle(-121.542)
1.5608
```

のように`:start-grasp`だけ返り値がpositionになりますが、

- `start-grasp`のようにアクチュエータを動かすことなくpositionが知りたい
- pr2-robot (eusモデル) でも知りたい

場合はすでに何か方法があるでしょうか？

**Comment by k-okada** [comment]
なんにもならないコメントですが，指間の距離ってかpublishされていなかったっけ？

--
◉ Kei Okada


2015-11-03 17:05 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by YoheiKakiuchi** [comment]
> なんにもならないコメントですが，指間の距離ってかpublishされていなかったっけ？

gripperのactionのフィードバックかstate？かに出てないですかね？

あとは、joint_statesを見るんでしょうか。

**Comment by k-okada** [comment]
https://github.com/PR2/pr2_controllers/blob/hydro-devel/pr2_controllers_msgs/action/Pr2GripperCommand.action
で result/state で出ていそうですね

**Comment by furushchev** [comment]
closed via #190
