### ISSUE TITLE
send *ri* :state :torque-vector の正しい挙動

### ISSUE THREAD

**Issue by YoheiKakiuchi** [jsk-ros-pkg/jsk_pr2eus#183]

**Comment by YoheiKakiuchi** [comment]
``` send *ri* :state :torque-vector``` の期待されている正しい挙動は何だったでしょうか？

現在は、 ```send robot :torque-vector``` の値が返ってきており、これは、
https://github.com/euslisp/jskeus/blob/master/irteus/irtrobot.l#L371
で計算された結果のトルク列になります。

``` send *ri* :state :torque-vector``` は、 joint_statesのeffort （計測されたトルク列）が返ってくることを
期待していました。
また、ぱっと見たところ  joint_statesのeffort  を返すためのメソッドが無いように思うのですが
いかがでしょうか？

**Comment by snozawa** [comment]
Closed via https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/198.
