### ISSUE TITLE
pr2の脱力モード

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_pr2eus#271]
pr2で片腕のみ脱力させる、といったことをしようとしているのですが、pr2 teleop joyはどのように マネキンと脱力とサーボを切り替えているのでしょうか。（コードはどこにありますか？）
pr2_teleop_general_joystick.launchを見ているのですが、どこが該当しているのか見つけられていません。

by @h-kamada

**Comment by furushchev** [comment]
だいぶ前のコードですが、僕はこんな感じで切り替えて使っていた覚えがあります。

https://github.com/jsk-ros-pkg/euslib/blob/master/demo/furushchev/ros_local_repo/local_pr2_demo/euslisp/test-util.l

**Comment by h-kamada** [comment]
なるほど、ありがとうございます。
こちらのサイトも読んでいたのですが、
http://wiki.ros.org/pr2_controller_manager
switch controllerのサービスはあくまでも何かのcontrollerから別へ変えるものだと思い込んでました。
が、よく読んでみるとstart引数をnilにも出来るようなのでこれで良いのですね！ありがとうございます。

**Comment by furushchev** [comment]
@h-kamada 落ち着いたらでいいので、使えることがわかったコードを綺麗な形でpr2eusにプルリクエストシていただけると助かります。

**Comment by k-okada** [comment]
https://github.com/PR2/pr2_apps/tree/hydro-devel/pr2_mannequin_mode/launch

コントローラ変えているみたいですね．

--
◉ Kei Okada


2016-12-09 0:32 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@h-kamada ping

**Comment by h-kamada** [comment]
こちらの方忘れてました。
修論の際、eusからコントローラを変えようとした際に変なエラーが出て、仕方ないのでコマンドラインからswitchする形でやり繰りしてました。
修論も落ち着いたので、もう一度eusからswitchするコードを書いてみます。

**Comment by furushchev** [comment]
This feature is now available from https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/295
