### ISSUE TITLE
end-coords-interpolation cannot take less than 10s 

### ISSUE THREAD

**Issue by pazeshun** [jsk-ros-pkg/jsk_pr2eus#354]
```
(send *robot* :rarm :move-end-pos #f(0 0 300) :world)
(send *ri* :angle-vector (send *robot* :angle-vector) 1000 nil 0 :end-coords-interpolation t)
```
does not move robot in 1 second, but 10 seconds.

**Comment by Affonso-Gui** [comment]
try playing around with `:end-coords-interpolation-steps` and `:min-time`

**Comment by pazeshun** [comment]
`:angle-vector`'s default `min-time` is 1 sec.
This is applied to interpolated steps of `end-coords-interpolation`.
`end-coords-interpolation-steps`'s default value is 10, so execution time becomes 1 * 10 = 10 secs.

@Affonso-Gui Thank you for your comment. I already found solution. See #355

**Comment by pazeshun** [comment]
> :angle-vector's default min-time is 1 sec.
> This is applied to interpolated steps of end-coords-interpolation.
> end-coords-interpolation-steps's default value is 10, so execution time becomes 1 * 10 = 10 secs.

Maybe this is confusing behavior because usual `:angle-vector`'s `min-time` is minimum time for whole execution.
