### ISSUE TITLE
少し前に抜けるwait-interplolation 的なものの作成

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_pr2eus#74]
r_arm_controller/state
として出てくる以下のメッセージの中のerrorの値をしきい値と比較してset succeedなどをしているので、この部分を使ってだいたいできたら抜けるようなwait-interpolationを作成する。

header:
  seq: 17188037
  stamp:
    secs: 1418625602
    nsecs: 793395399
  frame_id: ''
joint_names: ['r_shoulder_pan_joint', 'r_shoulder_lift_joint', 'r_upper_arm_roll_joint', 'r_elbow_flex_joint', 'r_forearm_roll_joint', 'r_wrist_flex_joint', 'r_wrist_roll_joint']
desired:
  positions: [-0.023607267439269997, 1.1065002721060977, -1.5567758652671915, -2.1221670650093913, -1.4174727684520152, -1.8417089607689183, 0.2143574279776601]
  velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  effort: []
  time_from_start:
    secs: 0
    nsecs: 0
actual:
  positions: [-0.01647729834656919, 1.101339981796726, -1.5678403482867136, -2.185142324461226, -1.7655965377204885, -1.841143344807624, 0.21405286553696357]
  velocities: [0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0]
  accelerations: []
  effort: []
  time_from_start:
    secs: 0
    nsecs: 0
error:
  positions: [-0.007129969092700805, 0.005160290309371707, 0.01106448301952212, 0.06297525945183446, 0.3481237692684733, -0.0005656159612943412, 0.00030456244069654304]
  velocities: [0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0]
  accelerations: []
  effort: []
  time_from_start:
    secs: 0
    nsecs: 0

**Comment by k-okada** [comment]
@h-kamada マージしても大丈夫そうかな？

**Comment by k-okada** [comment]
僕だったら，（https://github.com/github/hub/tree/1.11-stable）をつかって
```
sudo apt-get install gem
sudo apt-get install hub
roscd pr2eus
hub remote add k-okada
git fetch --all
git checkout add_interpolation_smooth
```
で変更がこのブランチになるとおもいます．マージされたら
```
git checkout master
git  pull origin/master
```
かな．

**Comment by k-okada** [comment]
closed via #88
