### ISSUE TITLE
:wait-interpolation returns nil when simulation mode

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_pr2eus#92]
this is just a question.
is there any reason that `:wait-interpolation` method should return nil when simulation mode?

**Comment by garaemon** [comment]
I think no reason for that...

**Comment by furushchev** [comment]
Thanks for answer. OK, I sent PR.
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/93
