### ISSUE TITLE
go-pos-unsafe does not work

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_pr2eus#99]
I' will dig this issue from now on

**Comment by garaemon** [comment]
It does not happen on pr1040, only pt1012.
And also it looks like low-level problem around base-controller because:
* go-pos looks slow
* go-pos-unsafe looks slow
* controlling via pr3 controller looks slow

I need to dig this issue but pr1012 has gone...

**Comment by furushchev** [comment]
Now I checked this problem still occurs doing fridge demo, in which it seems that pr2 go-pos-unsafe correctly and he finishes task to end. (PR1012)

**Comment by garaemon** [comment]
hmm, unfortunately it worked
